version: '3.1'

services:
  bot:
    build: ./bot
    command: python bot.py
    environment:
      BOT_TOKEN: 000000000000000000000
      DB_NAME: zenirlbot
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
    depends_on:
      - db
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_DB: zenirlbot
      POSTGRES_PASSWORD: password